### ISSUE TITLE
The reason the old system used xml

### ISSUE THREAD

**Issue by johnwhelan** [rileyzzz/BlenderIMExporter#6]
XML provided a method of filtering what went into the .im file.  Anything the importer didn't understand was ignored.  The problem with creating an .im file directly is you may cause problems in the game with a corrupt .im file.

The original system created a .im file directly.  It was later amended to add in the XML step to provide a degree of isolation.

**Comment by rileyzzz** [comment]
This is correct - unfortunately the old XML exporter was very slow. (and extremely prone to crashing)
Although that method may have worked for small meshes back in 2008, models these days have many more triangles. Writing out the positions, normals, texcoords, tangents, skinning, and other data for each vertex in the mesh as text-based XML, just for a separate program to instantly read that data back to generate an indexed mesh is frankly pointless (and probably introduces more stability issues than this exporter ever did).
TrainzMeshImporter was designed for simplicity and ease of use so people wouldn't accidentally introduce any issues by making their own poorly written exporters. Custom importers were unsupported by Auran (and are still unsupported by N3V), but quite frankly TrainzMeshImporter is unsupported by them too (seeing as it hasn't had an update in over a decade). It's worth noting that there's probably a large difference here between unsupported; as in "we aren't responsible for fixing your exporter if something breaks" - and directly opposed; "we recommend not writing to our format". As far as I'm aware, their position is the former. Several DEM software for Trainz do a similar thing (there's no such thing as TrainzMapImporter).
I have done extensive research on .im, and given that we know the purpose and function of every byte in the file it makes much more sense to write out an .im directly. I have verified that in many cases this exporter will output data identical to TrainzMeshImporter, and if not it's because it's using much more recent (official) chunk versions (used by the 3DSMax exporters) that support more features.
It's also worth noting that all of the official, built-in Blender exporters work like this too. IIRC i'm pretty sure Blender's FBX exporter (the one Blender content creators use to make Trainzmesh files today!) uses reverse engineered info about .fbx as well, and writes to the format just like we do, rather than using Autodesk's official FBX SDK.
Feature-wise, my exporter gives us the ability to use many more features than TrainzMeshImporter ever did (as evidenced by the number of export parameters), and is designed with general JET usage in mind rather that just Trainz. It's unlikely that anyone will ever make another game using JET, but if they did we're (to my knowledge) perfectly conformant with the spec 🙂
